[pytest]
testpaths = tests
pythonpath = .
addopts = -v --html=reports/reporte.html --self-contained-html
log_cli = true
log_cli_level = INFO
log_file = reports/ejecucion.log
log_file_level = INFO
log_file_mode = w
log_format = %(asctime)s | %(levelname)s | %(name)s | %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
markers =
    login: validación del inicio de sesión
    catalogo: validación del inventario y su interfaz
    carrito: incorporación y verificación de productos en el carrito
